### PR TITLE
feat/dataset_from_db

### PR DESCRIPTION
**Pull request by fraiss-c**

### CODE REVIEW

**Comment by beurie-v** [comment]
Would be cool to have a screenshot of a result in the dataset table

**Comment by beurie-v** [comment]
Also, it seems don't save the result in the database ?

**Comment by beurie-v** [comment]
The dataset storage in done in your other PR, I think you should either work on merging it and rebasing this branch with master to have the dataset table or erase this branch entirely and push your changes to the same branch as your other PR

**Comment by fraiss-c** [comment]
The dataset is still created in a file, this mr is about creating the dataset from the DB not storing it in DB

**Pull request merged**
